/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import gamedcheroes.Partida;
import java.awt.Color;
import utilitarios.Dificuldade;

/**
 *
 * @author rafael
 */
public class TelaSelecionaDificuldade extends javax.swing.JFrame {

    Partida partida;

    /**
     * Creates new form TelaSelecionaDificuldade
     * @param partida Objeto partida referente ao jogo
     */
    public TelaSelecionaDificuldade(Partida partida) {
        this.getContentPane().setBackground(Color.white);
        this.partida = partida;
        initComponents();
        jRadioButtonNormal.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jRadioButtonFacil = new javax.swing.JRadioButton();
        jRadioButtonNormal = new javax.swing.JRadioButton();
        jRadioButtonDificil = new javax.swing.JRadioButton();
        jRadioButtonInsano = new javax.swing.JRadioButton();
        jLabelQualADificuldade = new javax.swing.JLabel();
        jLabelDaPartida = new javax.swing.JLabel();
        jButtonJogar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRadioButtonFacil.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(jRadioButtonFacil);
        jRadioButtonFacil.setText("Fácil");

        jRadioButtonNormal.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(jRadioButtonNormal);
        jRadioButtonNormal.setText("Normal");

        jRadioButtonDificil.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(jRadioButtonDificil);
        jRadioButtonDificil.setText("Difícil");

        jRadioButtonInsano.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(jRadioButtonInsano);
        jRadioButtonInsano.setText("Insano");

        jLabelQualADificuldade.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabelQualADificuldade.setForeground(new java.awt.Color(59, 95, 161));
        jLabelQualADificuldade.setText("Qual a dificuldade");

        jLabelDaPartida.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabelDaPartida.setForeground(new java.awt.Color(59, 95, 161));
        jLabelDaPartida.setText("da Partida?");

        jButtonJogar.setText("Jogar");
        jButtonJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJogarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonInsano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButtonDificil)
                            .addComponent(jRadioButtonNormal)
                            .addComponent(jRadioButtonFacil))
                        .addGap(87, 87, 87))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabelQualADificuldade)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonJogar)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabelDaPartida)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelQualADificuldade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDaPartida)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonFacil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonNormal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonDificil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonInsano)
                .addGap(18, 18, 18)
                .addComponent(jButtonJogar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        
    //<editor-fold defaultstate="collapsed" desc="Eventos">

    private void jButtonJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJogarActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonFacil.isSelected()) {
            partida.getEquipeComputador().implementaDificuldade(Dificuldade.FACIL);
        } else if (jRadioButtonNormal.isSelected()) {
            partida.getEquipeComputador().implementaDificuldade(Dificuldade.NORMAL);
        } else if (jRadioButtonDificil.isSelected()) {
            partida.getEquipeComputador().implementaDificuldade(Dificuldade.DIFICIL);
        } else {
            partida.getEquipeComputador().implementaDificuldade(Dificuldade.INSANO);
        }
        TelaPartida telaPartida = new TelaPartida(partida);
        telaPartida.setLocationRelativeTo(null);
        telaPartida.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonJogarActionPerformed

    //</editor-fold>

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButtonJogar;
    private javax.swing.JLabel jLabelDaPartida;
    private javax.swing.JLabel jLabelQualADificuldade;
    private javax.swing.JRadioButton jRadioButtonDificil;
    private javax.swing.JRadioButton jRadioButtonFacil;
    private javax.swing.JRadioButton jRadioButtonInsano;
    private javax.swing.JRadioButton jRadioButtonNormal;
    // End of variables declaration//GEN-END:variables
}
